# https://starship.rs/config/
# Use custom format
format = """
$env_var\
${custom.osicon}\
$username\
$hostname\
$time\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
${custom.docker}\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$crystal\
$memory_usage\
$cmd_duration\
$jobs\
$battery\
[î‚´](fg:#5a6374)\
$line_break\
$status\
$character"""

# Wait 30 milliseconds for starship to check files under the current directory.
scan_timeout = 30

# Disable the newline at the start of the prompt
add_newline = true

[aws]
symbol = "îŒ½ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$profile($region)]($style)"

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$percentage]($style)"

[[battery.display]]
threshold = 10
style = "bold fg:bright-red bg:#5a6374"

[[battery.display]]
threshold = 30
style = "bold fg:bright-yellow bg:#5a6374"

[character]
success_symbol = "[âžœ](bold bright-green) "
error_symbol = "[âœ—](bold bright-red) "
vicmd_symbol = "[V](bold bright-green) "

[cmake]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[cmd_duration]
min_time = 5_000  # Show command duration over 5,000 milliseconds (=5 sec)
style = "bold fg:bright-red bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[ï‰’ $duration]($style)"

[conda]
symbol = "ï„Œ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$environment]($style)"

[crystal]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[dart]
symbol = "îž˜ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[directory]
truncation_length = 5
truncation_symbol = ""
truncate_to_repo = false
style = "bold fg:bright-blue bg:#5a6374"
read_only_style = "bold fg:bright-red bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
"~" = "ï€• ~"

[docker]
symbol = "ïŒˆ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$context]($style)"

[dotnet]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version( ðŸŽ¯ $tfm)]($style)"

[elixir]
symbol = "î‰µ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version OTP $otp_version]($style)"

[elm]
symbol = "î˜¬ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[erlang]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[gcloud]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$account($region)]($style)"

[git_branch]
symbol = "ï˜ "
style = "bold fg:bright-purple bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$branch]($style)"

[git_commit]
style = "bold fg:bright-green bg:#5a6374"
format = "[ $hash]($style)"

[git_state]
style = "bold fg:bright-yellow bg:#5a6374"
format = "[ $state( $progress_current/$progress_total)]($style)"

[git_status]
conflicted = " =${count}"
ahead = " â‡¡${count}"
behind = " â‡£${count}"
diverged = " â‡•â‡¡${ahead_count} â‡£${behind_count}"
untracked = " ?${count}"
stashed = " $${count}"
modified = " !${count}"
staged = " +${count}"
renamed = " Â»${count}"
deleted = " âœ˜${count}"
style = "bold fg:bright-red bg:#5a6374"
format = "[$all_status$ahead_behind]($style)"

[golang]
symbol = "î˜§ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[helm]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[hg_branch]
symbol = "ï˜ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$branch]($style)"

[hostname]
ssh_only = false
trim_at = "."
style = "bold fg:bright-yellow bg:#5a6374"
format = "[@$hostname]($style)"
disabled = false

[java]
symbol = "î‰– "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[jobs]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$number]($style)"

[julia]
symbol = "î˜¤ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[memory_usage]
symbol = "ï¡š "
show_percentage = true
show_swap = true
threshold = -1
separator = "/"
style = "bold fg:bright-yellow bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol${ram} ${ram_pct}( | ${swap} ${swap_pct})]($style)"
disabled = true

[nim]
symbol = "ïš¤ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[nix_shell]
symbol = "ï‹œ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$state( $name)]($style)"

[nodejs]
symbol = "î‰ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[ocaml]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[package]
symbol = "ï£– "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[perl]
symbol = "î© "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[php]
symbol = "î˜ˆ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[python]
scan_for_pyfiles = false
symbol = "î˜† "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[${symbol}${pyenv_prefix}${version}( $virtualenv)]($style)"

[ruby]
symbol = "îˆ¾ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[rust]
symbol = "ï€“ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[shlvl]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$shlvl]($style)"

[singularity]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol($env)]($style)"

[status]
style = "bold fg:bright-red bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$status]($style)"

[swift]
symbol = "ï¯£ "
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[terraform]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$workspace]($style)"

[zig]
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$version]($style)"

[time]
time_format = "%H:%M" # "%T" "%Y-%m-%d %H:%M:%S"
utc_time_offset = "+8"
style = "bold fg:bright-green bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[ï™ $time]($style)"
disabled = false

[username]
style_user = "bold fg:bright-cyan bg:#5a6374"
style_root = "bold fg:bright-red bg:#5a6374"
style = "bold fg:bright-cyan bg:#5a6374"
format = "[$user]($style)"
show_always = true
disabled = false

## linux
[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.yml files"
command = "echo ðŸ³"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
when = """ command -v docker &> /dev/null; exit (echo $?); """
style = "bold fg:bright-cyan bg:#5a6374"
format = "[ î‚µ ](fg:white bg:#5a6374)[$symbol$output]($style)"
disabled = false

[env_var]
variable = "OS_INFO_ICON"
default = "ï…¼"
style = "bold fg:bright-white bg:#5a6374"
format = "[$env_value ]($style)"
disabled = false

[custom.osicon]
command = "source $HOME/terminal-custom/custom_functions.sh && get_os_icon && echo ${OS_ICON}"
when = """ test true """
style = "bold fg:bright-white bg:#5a6374"
format = "[$symbol$output ]($style)"
disabled = true

[custom.homeicon]
command = "echo ï€•"
when = """ test "$HOME" = "$PWD" """
style = "bold fg:bright-white bg:#5a6374"
format = "[$symbol$output ]($style)"
disabled = true
